# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
# formats:
#   - pdf
#   - epub

# Optional but recommended, declare the Python requirements required
# to build your documentation
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

# Uncomment if you want PDF and EPUB builds
# formats:
#   - pdf
#   - epub

# Install dependencies needed for building docs
# We need to list the required packages for building the docs
# This section is what to put in pyproject.toml
# [tool.poetry.group.docs.dependencies]
# sphinx = "^7.1.2"
# sphinx-rtd-theme = "^1.3.0"
# myst-parser = "^2.0.0" 