name: Build and Release

on:
  push:
    tags: [ 'v*' ]
  workflow_dispatch:  # Allow manual triggering
    inputs:
      version:
        description: 'If this is a release what version is this for? If this is a pre-release what version are you developing toward?'
        required: true
        type: string

jobs:
  build-wheels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

